// Wygenerowane przez scripts/ects-program.ts z Katalogu ECTS PW (2021/2022) - nie edytować ręcznie.
export const PROGRAM_NAMES: string[] = [
 "HES sem. 1",
 "Anatomia i fizjologia",
 "Metrologia",
 "Propedeutyka medycyny",
 "Podstawy programowania",
 "Fizyka 1",
 "Matematyka - Algebra liniowa",
 "Matematyka - Analiza I",
 "Materiałoznawstwo",
 "Szkolenie BHP",
 "HES sem.2",
 "Biomateriały",
 "Fizykomedyczne podstawy inżynierii biomedycznej",
 "Programowanie obiektowe",
 "Fizyka 2",
 "Matematyka - Analiza 2",
 "Mechanika i Wytrzymałość materiałów",
 "Wstęp do elektrotechniki",
 "Grafika komputerowa",
 "Laboratorium elektrotechniki",
 "Podstawy Automatyki",
 "Podstawy elementów i układów elektronicznych",
 "Radiologia",
 "Wspomagane komputerowo projektowanie inżynierskie",
 "Matematyka - Rachunek prawdopodobieństwa i statystyka",
 "Biomechanika inżynierska",
 "Metody numeryczne",
 "Podstawy obrazowania medycznego",
 "Podstawy Robotyki",
 "Sensory i pomiary wielkości nieelektrycznych",
 "Sygnały i systemy",
 "Wstęp do systemów elektroniki wbudowanej",
 "Programowalne Układy Logiczne",
 "Technika mikroprocesorowa",
 "Układy elektroniczne",
 "Akceleratory biomedyczne",
 "Akwizycja i przetwarzanie danych z wykorzystaniem LabVIEW",
 "Analiza danych pomiarowych w medycynie",
 "Biometryczna identyfikacja tożsamości",
 "Detekcja promieniowania jonizującego",
 "Informatyczne systemy medyczne",
 "Kontrola Jakości Radiologicznych Urządzeń Diagnostycznych",
 "Metoda elementów skończonych – zastosowanie w bioinżynierii",
 "Napędy elektromechaniczne urządzeń mechatronicznych",
 "Podstawy biostatystyki",
 "Podstawy modelowania w medycynie",
 "Programowanie i analiza danych w R",
 "Projektowanie obwodów drukowanych – program PADS",
 "Projektowanie wyrobów medycznych",
 "Przyrządy optyczne w medycynie",
 "Przyrządy w elektroterapii serca",
 "Systemy długotrwałego monitorowania",
 "Technika ultradźwiękowa w diagnostyce medycznej",
 "Techniki laserowe w biomedycynie – biofotonika",
 "Techniki medycyny nuklearnej (IBM)",
 "Wprowadzenie do programowania w MATLABie",
 "Elektroniczna aparatura medyczna I",
 "Laboratorium Automatyki i Robotyki",
 "Przedmioty obieralne sem. 6",
 "Cyfrowe przetwarzanie obrazów",
 "Pracownia problemowa",
 "Praktyka przeddyplomowa",
 "Praca dyplomowa",
 "Seminarium dyplomowe"
]
